-- MySQL Script generated by MySQL Workbench
-- Mon Dec  7 21:32:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MakeMeRun
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MakeMeRun` ;

-- -----------------------------------------------------
-- Schema MakeMeRun
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MakeMeRun` DEFAULT CHARACTER SET utf8 ;
USE `MakeMeRun` ;

-- -----------------------------------------------------
-- Table `MakeMeRun`.`KLUB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`KLUB` (
  `ID` INT NOT NULL,
  `Ime kluba` VARCHAR(45) NULL,
  `Adresa` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Broj telefona` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`AIMS Certifikat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`AIMS Certifikat` (
  `Broj` VARCHAR(20) NOT NULL,
  `Certifikator` VARCHAR(45) NULL,
  `Pocetak` VARCHAR(30) NULL,
  `Kraj` VARCHAR(30) NULL,
  `Trka` VARCHAR(45) NULL,
  `Duzina` VARCHAR(45) NULL,
  `Naziv fajla` VARCHAR(45) NULL,
  PRIMARY KEY (`Broj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`ARHIVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`ARHIVA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Naziv trke` VARCHAR(40) NOT NULL,
  `Datum` VARCHAR(30) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`TRKA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`TRKA` (
  `Naziv` VARCHAR(30) NOT NULL,
  `Distanca` INT NOT NULL,
  `Datum` VARCHAR(45) NOT NULL,
  `Napomena` VARCHAR(45) NULL,
  `KLUB_ID` INT NOT NULL,
  `AIMS Certifikat_Broj` VARCHAR(20) NOT NULL,
  `ARHIVA_ID` INT NOT NULL,
  PRIMARY KEY (`Naziv`, `KLUB_ID`, `AIMS Certifikat_Broj`, `ARHIVA_ID`),
  INDEX `fk_TRKA_KLUB1_idx` (`KLUB_ID` ASC) VISIBLE,
  INDEX `fk_TRKA_AIMS Certifikat1_idx` (`AIMS Certifikat_Broj` ASC) VISIBLE,
  INDEX `fk_TRKA_ARHIVA1_idx` (`ARHIVA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TRKA_KLUB1`
    FOREIGN KEY (`KLUB_ID`)
    REFERENCES `MakeMeRun`.`KLUB` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRKA_AIMS Certifikat1`
    FOREIGN KEY (`AIMS Certifikat_Broj`)
    REFERENCES `MakeMeRun`.`AIMS Certifikat` (`Broj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRKA_ARHIVA1`
    FOREIGN KEY (`ARHIVA_ID`)
    REFERENCES `MakeMeRun`.`ARHIVA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`Redar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`Redar` (
  `JMBG` VARCHAR(45) NOT NULL,
  `Ime` VARCHAR(45) NOT NULL,
  `Prezime` VARCHAR(45) NOT NULL,
  `Uloga` VARCHAR(150) NULL,
  `Broj telefona` VARCHAR(45) NULL,
  PRIMARY KEY (`JMBG`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`Zaduzuje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`Zaduzuje` (
  `Zaduženje` VARCHAR(45) NOT NULL,
  `KLUB_ID` INT NOT NULL,
  `Redar_JMBG` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`KLUB_ID`, `Redar_JMBG`),
  INDEX `fk_Zaduzuje_KLUB1_idx` (`KLUB_ID` ASC) VISIBLE,
  INDEX `fk_Zaduzuje_Redar1_idx` (`Redar_JMBG` ASC) VISIBLE,
  CONSTRAINT `fk_Zaduzuje_KLUB1`
    FOREIGN KEY (`KLUB_ID`)
    REFERENCES `MakeMeRun`.`KLUB` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zaduzuje_Redar1`
    FOREIGN KEY (`Redar_JMBG`)
    REFERENCES `MakeMeRun`.`Redar` (`JMBG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`PREDSJEDNIK KLUBA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`PREDSJEDNIK KLUBA` (
  `ID` INT NOT NULL,
  `Ime` VARCHAR(45) NOT NULL,
  `Prezime` VARCHAR(45) NOT NULL,
  `JMBG` VARCHAR(45) NOT NULL,
  `KLUB_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `KLUB_ID`),
  INDEX `fk_PREDSJEDNIK KLUBA_KLUB1_idx` (`KLUB_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PREDSJEDNIK KLUBA_KLUB1`
    FOREIGN KEY (`KLUB_ID`)
    REFERENCES `MakeMeRun`.`KLUB` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`PROMOTOR TRKE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`PROMOTOR TRKE` (
  `ID` INT NOT NULL,
  `Ime` VARCHAR(35) NULL,
  `Prezime` VARCHAR(45) NULL,
  `Ime trke` VARCHAR(45) NULL,
  `Kontakt` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`AKTIVNOST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`AKTIVNOST` (
  `ID` INT NOT NULL,
  `Datum` DATETIME NULL,
  `Opis` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`PROMOVISE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`PROMOVISE` (
  `TRKA_Naziv` VARCHAR(30) NOT NULL,
  `AKTIVNOST_ID` INT NOT NULL,
  `PROMOTOR TRKE_ID` INT NOT NULL,
  INDEX `fk_PROMOVISE_AKTIVNOST1_idx` (`AKTIVNOST_ID` ASC) VISIBLE,
  INDEX `fk_PROMOVISE_PROMOTOR TRKE1_idx` (`PROMOTOR TRKE_ID` ASC) VISIBLE,
  PRIMARY KEY (`TRKA_Naziv`, `AKTIVNOST_ID`, `PROMOTOR TRKE_ID`),
  CONSTRAINT `fk_PROMOVISE_TRKA1`
    FOREIGN KEY (`TRKA_Naziv`)
    REFERENCES `MakeMeRun`.`TRKA` (`Naziv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROMOVISE_AKTIVNOST1`
    FOREIGN KEY (`AKTIVNOST_ID`)
    REFERENCES `MakeMeRun`.`AKTIVNOST` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROMOVISE_PROMOTOR TRKE1`
    FOREIGN KEY (`PROMOTOR TRKE_ID`)
    REFERENCES `MakeMeRun`.`PROMOTOR TRKE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`TRKAC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`TRKAC` (
  `Broj` INT NOT NULL,
  `Ime` VARCHAR(45) NOT NULL,
  `Prezime` VARCHAR(45) NOT NULL,
  `Distanca` INT NOT NULL,
  `Godine` INT NOT NULL,
  `Drzava` VARCHAR(45) NULL,
  `Uplata` VARCHAR(6) NULL,
  `Kontakt` VARCHAR(45) NOT NULL,
  `Vrijeme` VARCHAR(45) NULL DEFAULT '00:00:00',
  `TRKA_Naziv` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Broj`),
  INDEX `fk_TRKAČ_TRKA1_idx` (`TRKA_Naziv` ASC) VISIBLE,
  CONSTRAINT `fk_TRKAČ_TRKA1`
    FOREIGN KEY (`TRKA_Naziv`)
    REFERENCES `MakeMeRun`.`TRKA` (`Naziv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`STARTNI PAKET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`STARTNI PAKET` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Cijena` INT NULL,
  `TRKA_Naziv` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`, `TRKA_Naziv`),
  INDEX `fk_STARTNI PAKET_TRKA1_idx` (`TRKA_Naziv` ASC) VISIBLE,
  CONSTRAINT `fk_STARTNI PAKET_TRKA1`
    FOREIGN KEY (`TRKA_Naziv`)
    REFERENCES `MakeMeRun`.`TRKA` (`Naziv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`RACUN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`RACUN` (
  `BrojRacuna` VARCHAR(45) NOT NULL,
  `Banka` VARCHAR(45) NULL,
  `KLUB_ID` INT NOT NULL,
  `Stanje racuna` INT NULL,
  PRIMARY KEY (`BrojRacuna`, `KLUB_ID`),
  INDEX `fk_RACUN_KLUB1_idx` (`KLUB_ID` ASC) VISIBLE,
  CONSTRAINT `fk_RACUN_KLUB1`
    FOREIGN KEY (`KLUB_ID`)
    REFERENCES `MakeMeRun`.`KLUB` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`PRIZNANICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`PRIZNANICA` (
  `Tip` VARCHAR(45) NOT NULL,
  `Cijena` INT NULL,
  `Datum` DATETIME NULL,
  `RACUN_BrojRacuna` VARCHAR(30) NOT NULL,
  `TRKAČ_Broj` INT NOT NULL,
  INDEX `fk_PRIZNANICA_RACUN1_idx` (`RACUN_BrojRacuna` ASC) VISIBLE,
  PRIMARY KEY (`TRKAČ_Broj`),
  CONSTRAINT `fk_PRIZNANICA_RACUN1`
    FOREIGN KEY (`RACUN_BrojRacuna`)
    REFERENCES `MakeMeRun`.`RACUN` (`BrojRacuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRIZNANICA_TRKAČ1`
    FOREIGN KEY (`TRKAČ_Broj`)
    REFERENCES `MakeMeRun`.`TRKAC` (`Broj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`MEDIJSKI SARADNIK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`MEDIJSKI SARADNIK` (
  `ID` INT NOT NULL,
  `Ime` VARCHAR(30) NOT NULL,
  `Broj telefona` VARCHAR(45) NULL,
  `Adresa` VARCHAR(45) NULL,
  `Tip saradnje` VARCHAR(45) NULL,
  `Datum` DATETIME NULL,
  `TRKA_Naziv` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_MEDIJSKI SARADNICI_TRKA1_idx` (`TRKA_Naziv` ASC) VISIBLE,
  CONSTRAINT `fk_MEDIJSKI SARADNICI_TRKA1`
    FOREIGN KEY (`TRKA_Naziv`)
    REFERENCES `MakeMeRun`.`TRKA` (`Naziv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`SPONZOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`SPONZOR` (
  `ID` INT NOT NULL,
  `Ime` VARCHAR(40) NOT NULL,
  `Adresa` VARCHAR(45) NOT NULL,
  `Kontakti` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`UGOVOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`UGOVOR` (
  `Broj` INT NOT NULL,
  `Sadrzaj` VARCHAR(300) NULL,
  `Cijena` INT NULL,
  PRIMARY KEY (`Broj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`Potpisuju`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`Potpisuju` (
  `UGOVOR_Broj` INT NOT NULL,
  `SPONZORI_ID` INT NOT NULL,
  `PREDSJEDNIK KLUBA_ID` INT NOT NULL,
  PRIMARY KEY (`UGOVOR_Broj`, `SPONZORI_ID`, `PREDSJEDNIK KLUBA_ID`),
  INDEX `fk_Potpisuju_UGOVOR1_idx` (`UGOVOR_Broj` ASC) VISIBLE,
  INDEX `fk_Potpisuju_SPONZORI1_idx` (`SPONZORI_ID` ASC) VISIBLE,
  INDEX `fk_Potpisuju_PREDSJEDNIK KLUBA1_idx` (`PREDSJEDNIK KLUBA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Potpisuju_UGOVOR1`
    FOREIGN KEY (`UGOVOR_Broj`)
    REFERENCES `MakeMeRun`.`UGOVOR` (`Broj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Potpisuju_SPONZORI1`
    FOREIGN KEY (`SPONZORI_ID`)
    REFERENCES `MakeMeRun`.`SPONZOR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Potpisuju_PREDSJEDNIK KLUBA1`
    FOREIGN KEY (`PREDSJEDNIK KLUBA_ID`)
    REFERENCES `MakeMeRun`.`PREDSJEDNIK KLUBA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`PROIZVODJAC OPREME`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`PROIZVODJAC OPREME` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Tip proizvoda` VARCHAR(45) NULL,
  `Kontakt` VARCHAR(45) NULL,
  `Ime` VARCHAR(45) NULL,
  `KLUB_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PROIZVODJACI OPREME_KLUB1_idx` (`KLUB_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PROIZVODJACI OPREME_KLUB1`
    FOREIGN KEY (`KLUB_ID`)
    REFERENCES `MakeMeRun`.`KLUB` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`OPREMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`OPREMA` (
  `Id` INT NOT NULL,
  `Tip` VARCHAR(45) NULL,
  `Cijena` INT NULL,
  `Kolicina` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`Proizvodnja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`Proizvodnja` (
  `OPREMA_Id` INT NOT NULL,
  `PROIZVODJACI OPREME_ID` INT NOT NULL,
  PRIMARY KEY (`OPREMA_Id`, `PROIZVODJACI OPREME_ID`),
  INDEX `fk_Proizvođač opreme_has_OPREMA_OPREMA1_idx` (`OPREMA_Id` ASC) VISIBLE,
  INDEX `fk_Proizvodjac opreme_has_OPREMA_PROIZVODJACI OPREME1_idx` (`PROIZVODJACI OPREME_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Proizvođač opreme_has_OPREMA_OPREMA1`
    FOREIGN KEY (`OPREMA_Id`)
    REFERENCES `MakeMeRun`.`OPREMA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proizvodjac opreme_has_OPREMA_PROIZVODJACI OPREME1`
    FOREIGN KEY (`PROIZVODJACI OPREME_ID`)
    REFERENCES `MakeMeRun`.`PROIZVODJAC OPREME` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`REZULTAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`REZULTAT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Trkac` VARCHAR(45) NULL,
  `Vrijeme` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.` FOTOGRAFIJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.` FOTOGRAFIJA` (
  `Broj slike` INT NOT NULL AUTO_INCREMENT,
  `Naziv trke` VARCHAR(45) NOT NULL,
  `Ime fotografa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Broj slike`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`Cuvanje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`Cuvanje` (
  `ARHIVA_ID` INT NOT NULL,
  `FOTOGRAFIJA_Broj slike` INT NOT NULL,
  `REZULTAT_ID` INT NOT NULL,
  PRIMARY KEY (`ARHIVA_ID`, `FOTOGRAFIJA_Broj slike`, `REZULTAT_ID`),
  INDEX `fk_Cuvanje_ARHIVA1_idx` (`ARHIVA_ID` ASC) VISIBLE,
  INDEX `fk_Cuvanje_ FOTOGRAFIJA1_idx` (`FOTOGRAFIJA_Broj slike` ASC) VISIBLE,
  INDEX `fk_Cuvanje_REZULTAT1_idx` (`REZULTAT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Cuvanje_ARHIVA1`
    FOREIGN KEY (`ARHIVA_ID`)
    REFERENCES `MakeMeRun`.`ARHIVA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cuvanje_ FOTOGRAFIJA1`
    FOREIGN KEY (`FOTOGRAFIJA_Broj slike`)
    REFERENCES `MakeMeRun`.` FOTOGRAFIJA` (`Broj slike`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cuvanje_REZULTAT1`
    FOREIGN KEY (`REZULTAT_ID`)
    REFERENCES `MakeMeRun`.`REZULTAT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`SADRZAJ PAKETA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`SADRZAJ PAKETA` (
  `Carape` TINYTEXT NULL,
  `Znojnica` TINYTEXT NULL,
  `Torba` TINYTEXT NULL,
  `Karte za muzej` TINYTEXT NULL,
  `Majica` TINYTEXT NULL,
  `Energetski gel` TINYTEXT NULL,
  `Rucak` TINYTEXT NULL,
  `Bon za kupovinu` TINYTEXT NULL,
  `Vrecica za patike` TINYTEXT NULL,
  `Bandana` TINYTEXT NULL,
  `Pokloni sponzora` TINYTEXT NULL,
  `STARTNI PAKET_ID` INT NOT NULL,
  PRIMARY KEY (`STARTNI PAKET_ID`),
  CONSTRAINT `fk_SADRZAJ PAKETA_STARTNI PAKET1`
    FOREIGN KEY (`STARTNI PAKET_ID`)
    REFERENCES `MakeMeRun`.`STARTNI PAKET` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`KONTAKTIRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`KONTAKTIRA` (
  `MEDIJSKI SARADNICI_ID` INT NOT NULL,
  `PROMOTOR TRKE_ID` INT NOT NULL,
  PRIMARY KEY (`MEDIJSKI SARADNICI_ID`, `PROMOTOR TRKE_ID`),
  INDEX `fk_PROMOTOR TRKE_has_MEDIJSKI SARADNICI_MEDIJSKI SARADNICI1_idx` (`MEDIJSKI SARADNICI_ID` ASC) VISIBLE,
  INDEX `fk_KONTAKTIRA_PROMOTOR TRKE1_idx` (`PROMOTOR TRKE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PROMOTOR TRKE_has_MEDIJSKI SARADNICI_MEDIJSKI SARADNICI1`
    FOREIGN KEY (`MEDIJSKI SARADNICI_ID`)
    REFERENCES `MakeMeRun`.`MEDIJSKI SARADNIK` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KONTAKTIRA_PROMOTOR TRKE`
    FOREIGN KEY (`PROMOTOR TRKE_ID`)
    REFERENCES `MakeMeRun`.`PROMOTOR TRKE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`CLAN KLUBA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`CLAN KLUBA` (
  `ID` INT NOT NULL,
  `Ime` VARCHAR(45) NOT NULL,
  `Prezime` VARCHAR(45) NOT NULL,
  `Kontakt` VARCHAR(45) NULL,
  `Uloga` VARCHAR(45) NULL,
  `KLUB_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `KLUB_ID`),
  INDEX `fk_CLAN KLUBA_KLUB1_idx` (`KLUB_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CLAN KLUBA_KLUB1`
    FOREIGN KEY (`KLUB_ID`)
    REFERENCES `MakeMeRun`.`KLUB` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`KONTAKT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`KONTAKT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Ime kontakta` VARCHAR(45) NULL,
  `Opis` VARCHAR(45) NULL,
  `Kontakt` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MakeMeRun`.`IZVOD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`IZVOD` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Racun` VARCHAR(45) NULL,
  `Tip` VARCHAR(45) NULL,
  `Datum` DATETIME NULL,
  `Stanje` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

USE `MakeMeRun` ;

-- -----------------------------------------------------
-- Placeholder table for view `MakeMeRun`.`TRKAiAIMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`TRKAiAIMS` (`Naziv` INT, `AIMS Certifikat_Broj` INT);

-- -----------------------------------------------------
-- Placeholder table for view `MakeMeRun`.`pregledRezultata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MakeMeRun`.`pregledRezultata` (`Naziv trke` INT, `Trkac` INT, `Vrijeme` INT);

-- -----------------------------------------------------
-- procedure dupliraniKontakt
-- -----------------------------------------------------

DELIMITER $$
USE `MakeMeRun`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `dupliraniKontakt`(IN ime VARCHAR(30))
BEGIN
	SET @number=(SELECT COUNT(*) FROM `KONTAKT` WHERE `Kontakt`.`Ime kontakta`=ime);
	IF (@number>0) THEN
          DELETE FROM `Kontakt` WHERE `Ime kontakta`=ime;
    END IF;  
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure dodajKontakt
-- -----------------------------------------------------

DELIMITER $$
USE `MakeMeRun`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `dodajKontakt`(IN ime VARCHAR(30),IN opis VARCHAR(30),IN kontakt VARCHAR(30))
BEGIN
				INSERT INTO `Kontakt`(`Ime kontakta`,`Opis`,`Kontakt`)
                VALUES (ime,opis,kontakt);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure dodajIzvod
-- -----------------------------------------------------

DELIMITER $$
USE `MakeMeRun`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `dodajIzvod` (IN racun VARCHAR(45),IN tip VARCHAR(45), IN stanje INT)
BEGIN
    SET @datum := (SELECT NOW());
    INSERT INTO `Izvod`(`Racun`,`Tip`,`Datum`,`Stanje`)
    VALUES(racun,tip,@datum,stanje);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure pregledRezultata
-- -----------------------------------------------------

DELIMITER $$
USE `MakeMeRun`$$
CREATE PROCEDURE `pregledRezultata` (IN idTrka INT,IN idRez INT)
BEGIN
		SELECT 
		  `ARHIVA`.`Naziv trke`, `Rezultat`.`Trkac`,`Rezultat`.`Vrijeme`
			FROM `ARHIVA`,`REZULTAT`,`Cuvanje`        
		WHERE `Cuvanje`.`ARHIVA_ID`=idTrka && `Cuvanje`.`REZULTAT_ID`=idRez;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure dodajVrijeme
-- -----------------------------------------------------

DELIMITER $$
USE `MakeMeRun`$$
CREATE PROCEDURE `dodajVrijeme` (IN vrijeme VARCHAR(45),IN id INT)
BEGIN
		UPDATE `Trkac`
        SET
        `Trkac`.`Vrijeme`=vrijeme
        WHERE `Trkac`.`Broj`=id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `MakeMeRun`.`TRKAiAIMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MakeMeRun`.`TRKAiAIMS`;
USE `MakeMeRun`;
CREATE  OR REPLACE VIEW `TRKAiAIMS` AS
SELECT 
	`TRKA`.`Naziv`,`TRKA`.`AIMS Certifikat_Broj`
FROM `TRKA`;

-- -----------------------------------------------------
-- View `MakeMeRun`.`pregledRezultata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MakeMeRun`.`pregledRezultata`;
USE `MakeMeRun`;
CREATE  OR REPLACE VIEW `pregledRezultata` AS
SELECT 
		`ARHIVA`.`Naziv trke`, `Rezultat`.`Trkac`,`Rezultat`.`Vrijeme`
FROM `ARHIVA`,`REZULTAT`,`Cuvanje`        
WHERE `ARHIVA`.`ID`=`Cuvanje`.`ARHIVA_ID` && `REZULTAT`.`ID`=`Cuvanje`.`REZULTAT_ID`;
USE `MakeMeRun`;

DELIMITER $$
USE `MakeMeRun`$$
CREATE DEFINER = CURRENT_USER TRIGGER `MakeMeRun`.`Redar_AFTER_INSERT` AFTER INSERT ON `Redar` FOR EACH ROW
BEGIN
	INSERT INTO `KONTAKT`(`Ime kontakta`,`Opis`,`Kontakt`)
    VALUES(CONCAT(NEW.Ime," ",New.Prezime),"Redar na trci",NEW.`Broj telefona`);
END$$

USE `MakeMeRun`$$
CREATE DEFINER = CURRENT_USER TRIGGER `MakeMeRun`.`Redar_AFTER_DELETE` AFTER DELETE ON `Redar` FOR EACH ROW
BEGIN
		DELETE FROM `Kontakt` WHERE `Ime kontakta`=old.`Ime`+" "+old.`Prezime`;
END$$

USE `MakeMeRun`$$
CREATE DEFINER = CURRENT_USER TRIGGER `MakeMeRun`.`PROMOTOR TRKE_AFTER_INSERT` AFTER INSERT ON `PROMOTOR TRKE` FOR EACH ROW
BEGIN
	INSERT INTO `KONTAKT`(`Ime kontakta`,`Opis`,`Kontakt`)
    VALUES(CONCAT(NEW.Ime," ",New.Prezime),"Kontakt",NEW.`Kontakt`);
END$$

USE `MakeMeRun`$$
CREATE DEFINER = CURRENT_USER TRIGGER `MakeMeRun`.`PRIZNANICA_AFTER_INSERT` AFTER INSERT ON `PRIZNANICA` FOR EACH ROW
BEGIN
        SET @racun=(SELECT `BrojRacuna` FROM `Racun` WHERE `Racun`.`BrojRacuna`=NEW.`RACUN_BrojRacuna`);
        SET @stanje=(SELECT `Stanje racuna` FROM `Racun` WHERE `Racun`.`BrojRacuna`=NEW.`RACUN_BrojRacuna`);
        SET @novostanje=@stanje+NEW.`Cijena`;
        UPDATE `Racun`
		SET `Stanje racuna`=@novostanje 
        WHERE `BrojRacuna`=NEW.`RACUN_BrojRacuna`;
        SET @tip="Uplata trke";
		CALL dodajIzvod(NEW.`RACUN_BrojRacuna`,@tip,@novostanje);
END$$

USE `MakeMeRun`$$
CREATE DEFINER = CURRENT_USER TRIGGER `MakeMeRun`.`MEDIJSKI SARADNIK_AFTER_INSERT` AFTER INSERT ON `MEDIJSKI SARADNIK` FOR EACH ROW
BEGIN
	INSERT INTO `KONTAKT`(`Ime kontakta`,`Opis`,`Kontakt`)
    VALUES(NEW.Ime,"Medijski saradnik",NEW.`Broj telefona`);
END$$

USE `MakeMeRun`$$
CREATE DEFINER = CURRENT_USER TRIGGER `MakeMeRun`.`SPONZOR_AFTER_INSERT` AFTER INSERT ON `SPONZOR` FOR EACH ROW
BEGIN
	INSERT INTO `KONTAKT`(`Ime kontakta`,`Opis`,`Kontakt`)
    VALUES(NEW.Ime,"Sponzor",NEW.`Kontakti`);
END$$

USE `MakeMeRun`$$
CREATE DEFINER = CURRENT_USER TRIGGER `MakeMeRun`.`UGOVOR_AFTER_INSERT` AFTER INSERT ON `UGOVOR` FOR EACH ROW
BEGIN
		SET @cijena=NEW.`Cijena`;
        SET @novoStanje=(SELECT `Stanje racuna` FROM `Racun` WHERE `BrojRacuna`="2423-100-434-40-00")+@cijena;
        UPDATE `Racun`
        SET `Stanje racuna`=@novostanje
		WHERE `BrojRacuna`="2423-100-434-40-00";   
        SET @broj="2423-100-434-40-00";
        SET @tip="Uplata sponzora";
        CALL dodajIzvod(@broj,@tip,@cijena);
END$$

USE `MakeMeRun`$$
CREATE DEFINER = CURRENT_USER TRIGGER `MakeMeRun`.`PROIZVODJAC OPREME_BEFORE_INSERT` BEFORE INSERT ON `PROIZVODJAC OPREME` FOR EACH ROW
BEGIN
			CALL `dupliraniKontakt`(NEW.`Ime`);
END$$

USE `MakeMeRun`$$
CREATE DEFINER = CURRENT_USER TRIGGER `MakeMeRun`.`PROIZVODJAC OPREME_AFTER_INSERT` AFTER INSERT ON `PROIZVODJAC OPREME` FOR EACH ROW
BEGIN

	CALL `dodajKontakt`(NEW.`Ime`,"Proizvodjac opreme",NEW.`Kontakt`);	
END$$

USE `MakeMeRun`$$
CREATE DEFINER = CURRENT_USER TRIGGER `MakeMeRun`.`OPREMA_BEFORE_INSERT` BEFORE INSERT ON `OPREMA` FOR EACH ROW
BEGIN
	SET @racun:=(SELECT MAX(`Stanje racuna`) FROM `Racun`);
    SET @brojRacuna=(SELECT `BrojRacuna` FROM `RACUN` WHERE `Stanje racuna`=@racun);
    SET @cijena=NEW.`Cijena`*NEW.`Kolicina`;
	IF(@racun>@cijena) THEN  
		SET @novostanje:=@racun-@cijena;
        UPDATE `Racun`
			SET `Racun`.`Stanje racuna` = @novostanje
        WHERE
			`Racun`.`Stanje racuna`=@racun;
		SET @tip="Kupovina opreme";
		CALL dodajIzvod(@brojRacuna,@tip,@novostanje);   
     ELSE
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='greska';
    END IF;        
END$$

USE `MakeMeRun`$$
CREATE DEFINER = CURRENT_USER TRIGGER `MakeMeRun`.`CLAN KLUBA_AFTER_INSERT` AFTER INSERT ON `CLAN KLUBA` FOR EACH ROW
BEGIN
	INSERT INTO `KONTAKT`(`Ime kontakta`,`Opis`,`Kontakt`)
    VALUES(CONCAT(NEW.Ime," ",New.Prezime),"Clan kluba",NEW.`Kontakt`);
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
